"""
ORCA Backend — PFZ API Router
GET  /api/v1/pfz/zones                — Candidate fishing zones
POST /api/v1/pfz/evaluate             — Re-score with custom weights
GET  /api/v1/pfz/zones/{id}/explain   — Natural-language explanation
GET  /api/v1/pfz/regions              — Indian Ocean region presets
"""
from fastapi import APIRouter, Depends, Query

from app.agents import pfz_agent
from app.core.security import verify_api_key
from app.schemas.envelope import DataStatus, make_envelope
from app.schemas.pfz import PFZEvaluateRequest

router = APIRouter(prefix="/pfz", tags=["PFZ"])


@router.get("/regions")
async def get_regions(_: None = Depends(verify_api_key)):
    """Returns Indian Ocean PFZ region presets."""
    regions = pfz_agent.get_regions()
    return make_envelope(data=[r.model_dump() for r in regions], data_status=DataStatus.DEMO)


@router.get("/zones")
async def get_pfz_zones(
    region_id: str = Query(default="kerala-coast"),
    lat: float = Query(default=9.93),
    lng: float = Query(default=76.27),
    radius_km: float = Query(default=200.0),
    target_date: str = Query(default=None),
    _: None = Depends(verify_api_key),
):
    """
    Returns PFZ candidate zones computed by deterministic algorithm.
    Connects to: PFZCandidateTable (/research/pfz page).
    """
    zones = pfz_agent.compute_pfz_zones(region_id)
    return make_envelope(
        data=[z.model_dump() for z in zones],
        data_status=DataStatus.DEMO,
        warnings=[
            "PFZ zones computed from Sobel gradient model on demo SST/CHL grids.",
            "Scores are deterministic — not generated by LLM.",
        ],
    )


@router.post("/evaluate")
async def evaluate_pfz(
    request: PFZEvaluateRequest,
    _: None = Depends(verify_api_key),
):
    """
    Re-scores PFZ zones with custom operator weights and thresholds.
    Connects to: PFZModelConfiguration sidebar (/research/pfz page).
    """
    zones = pfz_agent.compute_pfz_zones(
        request.region_id,
        weights=request.weights,
        thresholds=request.thresholds,
    )
    return make_envelope(
        data=[z.model_dump() for z in zones],
        data_status=DataStatus.DEMO,
    )


@router.get("/zones/{zone_id}/explain")
async def explain_pfz_zone(
    zone_id: str,
    region_id: str = Query(default="kerala-coast"),
    _: None = Depends(verify_api_key),
):
    """
    Returns natural-language explainability for a specific PFZ zone.
    The LLM interprets the deterministic scores — never creates them.
    """
    zones = pfz_agent.compute_pfz_zones(region_id)
    zone = next((z for z in zones if z.id == zone_id), zones[0] if zones else None)
    if zone is None:
        return make_envelope(data={"error": "Zone not found"}, data_status=DataStatus.DEMO)

    explanation = (
        f"{zone.name} ({zone.id}) achieves a composite suitability score of {zone.score}/100. "
        f"Primary driver: {zone.primary_factor}. "
        f"SST thermal gradient: {zone.sst_gradient} — "
        f"{'above' if zone.sst_reading > 28.0 else 'below'} seasonal norm. "
        f"Chlorophyll-a: {zone.chl_reading} mg/m³ (gradient: {zone.chl_gradient}). "
        f"Bottom depth: {zone.depth_m}m — suitable for demersal fishery."
    )
    return make_envelope(
        data={"zone_id": zone_id, "explanation": explanation, "score": zone.score, "factors": [f.model_dump() for f in zone.factors]},
        data_status=DataStatus.DEMO,
    )
